[tool.poetry]
name = "bumblebee"
version = "0.1.0"
description = "A social media for the poeple with love"
authors = ["The GodFathers"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
djangorestframework = "^3.12.4"
black = "^20.8b1"
psycopg2 = "^2.8.6"
Django = "^3.1.7"
Pillow = "^8.2.0"

[tool.poetry.dev-dependencies]
black = {version = "^20.8b1", allow-prereleases = true}
isort = {version = "^5.8.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
